project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("accounts/", include('accounts.urls'))
]

todo/urls.py
from django.urls import path
from django.views.generic import RedirectView
from todo.views.users_views import delete_user
from todo.views.projects_views import IndexView, ProjectView, ProjectUpdateView, ProjectDeleteView, ProjectCreateView
from todo.views.tasks_views import (
    TaskCreateView,
    TaskView,
    TaskUpdateView,
    TaskDeleteView,
)

app_name = "todo"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("tasks/", RedirectView.as_view(pattern_name="todo:index")),
    path("project/<int:pk>/tasks/add/", TaskCreateView.as_view(), name="task_add"),
    path("task/<int:pk>", TaskView.as_view(), name="task_view"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task_update_view"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete_view"),
    path("project/<int:pk>", ProjectView.as_view(), name="project_view"),
    path("project/<int:pk>/update/", ProjectUpdateView.as_view(), name="project_update_view"),
    path("project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete_view"),
    path("project/add/", ProjectCreateView.as_view(), name="project_add"),
    path("project/<int:project_id>/users/<int:user_id>", delete_user, name="project_users_delete")
]

todo/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

status_choices = [("new", "Новая"), ("in_progress", "В процессе"), ("done", "Сделано")]
type_choices = [("task", "Задача"), ("bug", "Ошибка"), ("enhancement", "Улучшение")]


class AbstractModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Время изменения")

    class Meta:
        abstract = True


# class TypeTask(AbstractModel):
#     name = models.TextField(max_length=3000, verbose_name="Задача", unique=True)
#     descript = models.TextField(max_length=400, null=True, blank=True, verbose_name='Описание')
#
#     def __str__(self):
#         return f'{self.id}. {self.name}'


class Task(AbstractModel):
    name = models.CharField(
        max_length=50, null=False, blank=False, verbose_name="Задача"
    )
    description = models.TextField(
        max_length=3000, null=True, blank=False, verbose_name="Описание"
    )
    status = models.ForeignKey(
        "todo.Status",
        on_delete=models.RESTRICT,
        verbose_name="Статус",
        related_name="tasks",
        blank=True,
    )
    type = models.ManyToManyField(
        "todo.Type",
        through="todo.TaskType",
        through_fields=("task", "type"),
        verbose_name="Тип",
        related_name="tasks",
        blank=True,
    )
    project = models.ForeignKey(
        "todo.Project",
        on_delete=models.RESTRICT,
        verbose_name="Проект",
        related_name="tasks",
        blank=True,
    )
    users_task = models.ForeignKey(get_user_model(), null=True, related_name='tasks', on_delete=models.CASCADE, verbose_name='Пользователь')

    def __str__(self):
        return f"{self.id}. {self.name}"


class Status(AbstractModel):
    status_name = models.CharField(
        max_length=31, choices=status_choices, verbose_name="Статус"
    )

    def __str__(self):
        return self.status_name


class Type(AbstractModel):
    type_name = models.CharField(
        max_length=31, choices=type_choices, verbose_name="Тип"
    )

    def __str__(self):
        return self.type_name


class TaskType(models.Model):
    task = models.ForeignKey(
        "todo.Task",
        related_name="task_type",
        on_delete=models.CASCADE,
        verbose_name="Задача",
    )
    type = models.ForeignKey(
        "todo.Type",
        related_name="type_task",
        verbose_name="Тип",
        on_delete=models.RESTRICT,
    )

    def __str__(self):
        return "{} | {}".format(self.task, self.type)


class Project(models.Model):
    project_name = models.CharField(
        max_length=50, null=False, blank=False, verbose_name="Проект"
    )
    project_description = models.TextField(
        max_length=3000, null=True, blank=False, verbose_name="Описание проекта"
    )
    start_project = models.DateField(null=True, blank=True, verbose_name="Начало проекта")
    end_project = models.DateField(null=True, blank=True, verbose_name="Завершение проекта")
    users = models.ManyToManyField(get_user_model(), related_name='projects', verbose_name='Пользователь')

    def __str__(self):
        return f"{self.id}. {self.project_name}"

    def get_absolute_url(self):
        return reverse('todo:project_view', kwargs={'pk': self.pk})

todo/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import widgets
from todo.models import Type, Status, Task, Project


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name', 'description', 'type', 'status', 'project')
    name = forms.CharField(max_length=50, required=True, label="Задача")
    description = forms.CharField(
        max_length=3000, required=True, label="Описание", widget=widgets.Textarea
    )
    # type = forms.ModelChoiceField(queryset=Type.objects.all(), label="Тип")
    status = forms.ModelChoiceField(queryset=Status.objects.all(), label="Статус")


class SimpleSearchForm(forms.Form):
    search = forms.CharField(required=False, label='Найти')


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('project_name', 'project_description', 'start_project', 'end_project', 'users')
        # project_name = forms.CharField(max_length=50, required=True, label="Проект")
        # project_description = forms.CharField(
        #     max_length=3000, required=True, label="Описание проекта", widget=widgets.Textarea
        # )
        # start_project = forms.DateField(label="Начало проекта")
        # end_project = forms.DateField(label="Завершение проекта")

todo/views/projects_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import reverse, render, redirect, get_object_or_404
from todo.models import Project
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from todo.forms import TaskForm, SimpleSearchForm, ProjectForm
from django.utils.http import urlencode
from django.db.models import Q


class IndexView(ListView):
    model = Project
    template_name = 'projects/index.html'
    context_object_name = 'projects'
    paginate_by = 5
    paginate_orphans = 0
    ordering = ('project_name',)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']
        return None

    def dispatch(self, request, *args, **kwargs):
        print(request.user)
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(project_name__icontains=self.search_value) |
                                       Q(project_description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context


class ProjectView(DetailView):
    model = Project
    template_name = "projects/project_view.html"


def project_view(request, *args, pk, **kwargs):
    project = get_object_or_404(Project, pk=pk)
    return render(request, "projects/project_view.html", {"project": project})


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "projects/project_update.html"
    model = Project
    form_class = ProjectForm
    permission_required = 'todo.change_project'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().users


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    model = Project
    success_url = '/'
    template_name = "projects/project_delete.html"

    def has_permission(self):
        return self.request.user.has_perm('todo.delete_project') or self.request.user == self.get_object().users


class ProjectCreateView(LoginRequiredMixin, CreateView):
    template_name = 'projects/project_create.html'
    model = Project
    fields = ['project_name', 'project_description', 'start_project', 'end_project', 'users']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.users = self.request.user
        self.object.save()
        form.save_m2m()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('todo:project_view', kwargs={'pk': self.object.pk})

todo/views/tasks_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, reverse, redirect, get_object_or_404
from todo.models import Task, status_choices, TaskType, Status, Type, type_choices, Project
from todo.forms import TaskForm
from django.views.generic import View, CreateView, UpdateView, DetailView, DeleteView


class TaskView(DetailView):
    model = Task
    template_name = "tasks/task_view.html"


def task_view(request, *args, pk, **kwargs):
    task = get_object_or_404(Task, pk=pk)
    return render(request, "tasks/task_view.html", {"task": task})


class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'tasks/task_create.html'
    model = Task
    form_class = TaskForm

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        task = form.save(commit=False)
        task.project = project
        task.save()
        return redirect('todo:project_view', pk=project.pk)


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = "tasks/task_update.html"
    model = Task
    form_class = TaskForm
    permission_required = 'todo.change_task'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().users_task

    def get_success_url(self):
        return reverse('todo:project_view', kwargs={'pk': self.object.project_id})


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/task_delete.html"
    permission_required = 'todo.delete_task'

    def has_permission(self):
        return super().has_permission() or self.request.user == self.get_object().users_task

    def get_success_url(self):
        return reverse('todo:project_view', kwargs={'pk': self.object.project_id})


    # def get(self, request, *args, **kwargs):
    #     task = get_object_or_404(Task, pk=kwargs.get("pk"))
    #     return render(
    #         request,
    #         "tasks/task_delete.html",
    #         {
    #             "status_choices": status_choices,
    #             "type_choices": type_choices,
    #             "task": task,
    #         },
    #     )

    # def post(self, request, *args, **kwargs):
    #     task = get_object_or_404(Task, pk=kwargs.get("pk"))
    #     task.delete()
    #     return redirect("todo:index")

todo/views/users_views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import reverse, render, redirect, get_object_or_404
from todo.models import Project
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView
from todo.forms import TaskForm, SimpleSearchForm, ProjectForm
from django.utils.http import urlencode
from django.db.models import Q


def delete_user(request, project_id, user_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        project = get_object_or_404(Project, pk=project_id)
        project.users.filter(id=user_id).delete()
        return redirect('todo:project_view', pk=project_id)
    user = get_user_model().objects.get(id=user_id)
    return render(request, 'projects/users_delete.html', {'user': user, 'project': project})

todo/templates/projects/index.html
{% extends 'base.html' %}

{% block menu %}
    {% if request.user.is_authenticated %}
        <a class="nav-link" aria-current="page" href="{% url 'todo:project_add' %}">Создать проект</a>
    {% endif %}
{% endblock %}

<body>
{% block content %}
    <h1>Мои проекты</h1>
    <div>
    {%  include 'partial/simple_search.html' %}
    </div>

    {% if is_paginated %}
    {% include 'partial/pagination.html' %}
    {%  endif %}

<div class="row row-cols-3">

    {% for project in projects %}
        <div class="col">
        <div class="card my-3" >
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <h6 class="card-subtitle mb-2 text-body-secondary">{{ project.project_description }}</h6>
{#                <p class="card-text">Types: {% for type in task.type.all %}#}
{#                    {{ type.type_name }}{% if forloop.last %}.{% else %},{% endif %}#}
{#                    {% endfor %}#}
{#                    </p>#}
                <a href={{ project.get_absolute_url }} class="card-link">Подробнее...</a>
                {% if request.user.is_authenticated %}
                {% if perms.todo.change_project or project.users == request.user %}
                    <a href={% url 'todo:project_update_view' pk=project.pk %} class="card-link">Редактировать</a>
                {% endif %}
                {% if perms.todo.delete_project or project.users == request.user %}
                    <a href={% url 'todo:project_delete_view' pk=project.pk %} class="card-link">Удалить</a>
                {% endif %}

                {% endif %}

            </div>
        </div>
        </div>

    {% endfor %}
</div>
{% endblock %}

todo/templates/projects/project_create.html
{% extends 'base.html' %}

{% block title %}Create project{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page" href={% url 'todo:index' %}>На главную</a>{% endblock %}


{% block content %}
<h1>Создать проект</h1>

<form action="/project/add/" method="post">
    {% csrf_token %}
    {% include 'partial/project_form.html' with value_submit='Create' %}
</form>


{% endblock %}

todo/templates/projects/project_delete.html
{% extends 'base.html' %}

{% block title %}Delete project{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page" href={% url 'todo:index' %}>На главную</a>{% endblock %}


{% block content %}
<h1>Удалить проект</h1>

    <h3>Вы уверены, что хотите удалить проект "{{ object }}"?</h3>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="ДА"/>
</form>
    <a href="{% url 'todo:project_view' pk=project.pk %}">Нет</a>


{% endblock %}

todo/templates/projects/project_update.html
{% extends 'base.html' %}

{% block title %}Update project{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page" href={% url 'todo:index' %}>На главную</a>{% endblock %}


{% block content %}
<h1>Редактировать проект</h1>

<form action="" method="post">
    {% include 'partial/project_form.html' with value_submit='Update' %}
</form>


{% endblock %}

todo/templates/projects/project_view.html
{% extends 'base.html' %}

{% block title %}{{ project.project_name }}{% endblock %}
{% block menu %}
    <a class="nav-link" aria-current="page" href={% url 'todo:index' %}>На главную</a>
    {% if request.user.is_authenticated %}
    {% if perms.todo.change_project or project.users == request.user %}
        <a class="nav-link" aria-current="page" href={% url 'todo:project_update_view' pk=project.pk %}>Редактировать</a>
    {% endif %}
    {% if perms.todo.delete_project or project.users == request.user %}
        <a class="nav-link" aria-current="page" href={% url 'todo:project_delete_view' pk=project.pk %}>Удалить</a>
    {% endif %}
        <a class="nav-link" aria-current="page" href={% url 'todo:task_add' pk=project.pk %}>Создать задачу</a>
    {% endif %}


{% endblock %}

{% block content %}

    <h3>Просмотр проекта </h3>

<div class="row">
    <div class="col-md-6">
        <div class="card" >
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">Users: {% for user in project.users.all %}{{ user.username }}, {% endfor %}</p>
                <p class="card-text">{{ project.project_description }}</p>
                <p class="card-text">Start: {{ project.start_project }}</p>
                <p class="card-text">End: {{ project.end_project }}</p>

            </div>
        </div>
    </div>
    <div class="col-md-6">
        <h4>Users</h4>
        <ul>
            {% for user in project.users.all %}
                <li>{{ user.username  }} <a href="{% url 'todo:project_users_delete' project.pk user.id %}">x</a></li>
            {% endfor %}
        </ul>
    </div>
</div>


    <h4>Мои задачи</h4>
    <div>

<div class="row row-cols-3">

    {% for task in project.tasks.all %}
        <div class="col">
        <div class="card my-3" >
            <div class="card-body">
                <h5 class="card-title">{{ task.name }}</h5>
                <p class="card-text">Users: {{ task.users_task }}</p>
                <h6 class="card-subtitle mb-2 text-body-secondary">{{ task.status }}</h6>
                <p class="card-text">Types: {% for type in task.type.all %}
                    {{ type.type_name }}{% if forloop.last %}.{% else %},{% endif %}
                    {% endfor %}
                    </p>
                <a href={% url 'todo:task_view' pk=task.pk %} class="card-link">Подробнее...</a>
                {% if request.user.is_authenticated %}
                {% if perms.todo.change_task or project.users == request.user %}
                    <a href={% url 'todo:task_update_view' pk=task.pk %} class="card-link">Редактировать</a>
                {% endif %}
                {% if perms.todo.delete_task or project.users == request.user %}
                    <a href={% url 'todo:task_delete_view' pk=task.pk %} class="card-link">Удалить</a>
                {% endif %}
                {% endif %}


            </div>
        </div>
        </div>

    {% endfor %}
</div>
{% endblock %}

todo/templates/projects/users_delete.html
{% extends 'base.html' %}

{% block title %}Delete user{% endblock %}
{% block menu %}<a class="nav-link" aria-current="page" href={% url 'todo:index' %}>На главную</a>{% endblock %}


{% block content %}
<h1>Удалить пользователя</h1>

    <h3>Вы уверены, что хотите удалить пользователя "{{ object }}"?</h3>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="ДА"/>
</form>
    <a href="{% url 'todo:project_view' pk=project.pk %}">Нет</a>


{% endblock %}